package genlab.gnuplot.algos;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintStream;

import genlab.core.commons.ProgramException;
import genlab.core.exec.IExecution;
import genlab.core.model.exec.AbstractAlgoExecutionOneshot;
import genlab.core.model.exec.ComputationProgressWithSteps;
import genlab.core.model.exec.ComputationResult;
import genlab.core.model.exec.ComputationState;
import genlab.core.model.exec.IAlgoExecution;
import genlab.core.model.exec.IAlgoExecutionContinuous;
import genlab.core.model.exec.IConnectionExecution;
import genlab.core.model.instance.IAlgoInstance;
import genlab.core.model.meta.basics.flowtypes.IGenlabTable;
import genlab.gnuplot.GnuplotUtils;

public class WriteGnuplotSkeletonExec 
						extends AbstractAlgoExecutionOneshot 
						implements IAlgoExecutionContinuous {

	public WriteGnuplotSkeletonExec(IExecution exec, IAlgoInstance algoInst) {
		super(exec, algoInst, new ComputationProgressWithSteps());
	}

	public WriteGnuplotSkeletonExec() {
	}

	@Override
	public long getTimeout() {
		// TODO Auto-generated method stub
		return 0;
	}


	/**
	 * Writes the table passed as a parameter to the file. 
	 * Throws exceptions in case of problem. 
	 * @param table
	 */
	protected void writeTableToFile(File file, IGenlabTable table) {

		try {
			PrintStream ps = new PrintStream(file);
			
			// header
			ps.println("# This file was automatically generated by GenLab to plot the content of a table");
			ps.println("");
			
			ps.println("# adapt to your file format");
			ps.println("set datafile separator \";\"");
			ps.println("");
			
			// add titles
			ps.println("# indices of columns");
			int i=1;
			for (String id : table.getColumnsId()) {
				ps.print("col_");
				ps.print(GnuplotUtils.toGnuplotVariableName(id));
				ps.print(" = ");
				ps.println(i++);
			}
			ps.println();
			
			// add column titles
			ps.println("# names of columns");
			i=1;
			for (String id : table.getColumnsId()) {
				ps.print("title_");
				ps.print(GnuplotUtils.toGnuplotVariableName(id));
				ps.print(" = \"");
				ps.print(id);
				ps.println("\"");
			}
			ps.println();
			
			// add example plot
			if (table.getColumnsCount()>=2) {
				ps.println("# example of 2d plot");
				
				ps.print("set xlabel title_");
				ps.println(GnuplotUtils.toGnuplotVariableName(table.getColumnIdForIdx(0)));
				ps.print("set ylabel title_");
				ps.println(GnuplotUtils.toGnuplotVariableName(table.getColumnIdForIdx(1)));
				
				ps.print("plot your_file_here using col_");
				ps.print(GnuplotUtils.toGnuplotVariableName(table.getColumnIdForIdx(0)));
				ps.print(":col_");
				ps.print(GnuplotUtils.toGnuplotVariableName(table.getColumnIdForIdx(1)));
				ps.println(" with points title \"something\"");
				
				ps.println();
				ps.println("pause -1");
				ps.println();
			}
			
			if (table.getColumnsCount()>=3) {
				ps.println("# example of 3d plot");
				
				ps.print("set xlabel title_");
				ps.println(GnuplotUtils.toGnuplotVariableName(table.getColumnIdForIdx(0)));
				ps.print("set ylabel title_");
				ps.println(GnuplotUtils.toGnuplotVariableName(table.getColumnIdForIdx(1)));
				ps.print("set zlabel title_");
				ps.println(GnuplotUtils.toGnuplotVariableName(table.getColumnIdForIdx(2)));
				
				ps.print("splot your_file_here using col_");
				ps.print(GnuplotUtils.toGnuplotVariableName(table.getColumnIdForIdx(0)));
				ps.print(":col_");
				ps.print(GnuplotUtils.toGnuplotVariableName(table.getColumnIdForIdx(1)));
				ps.print(":col_");
				ps.print(GnuplotUtils.toGnuplotVariableName(table.getColumnIdForIdx(2)));
				ps.println(" with points title \"something\"");
				
				ps.println();
				ps.println("pause -1");
				ps.println();
			}
			
			ps.close();
			
			
		} catch (RuntimeException e) {
			
			throw new ProgramException("an error occured during the writing of the table to a file: "+e.getMessage(), e);
			
		} catch (FileNotFoundException e) {
			
			throw new ProgramException("unable to create a file named \""+file+"\": "+e.getMessage(), e);
			
		}
	}
	
	@Override
	public void run() {

		progress.setComputationState(ComputationState.STARTED);
		
		final IGenlabTable table = (IGenlabTable)getInputValueForInput(WriteGnuplotSkeletonAlgo.INPUT_TABLE);
		final File file = (File)algoInst.getValueForParameter(WriteGnuplotSkeletonAlgo.PARAMETER_FILE);

		if (table == null)
			throw new ProgramException("no data available for computation");
		
		progress.setProgressTotal(10);
		
		try {
			writeTableToFile(file, table);
			
			// export the file as a result
			ComputationResult res = new ComputationResult(algoInst, progress, messages);
			res.setResult(WriteGnuplotSkeletonAlgo.OUTPUT_FILE, file);
			setResult(res);
			progress.setProgressMade(10);
			progress.setComputationState(ComputationState.FINISHED_OK);

		} catch (ProgramException e) {

			e.printStackTrace();
			messages.errorUser(e.getMessage(), getClass(), e);
			progress.setComputationState(ComputationState.FINISHED_FAILURE);
			progress.setException(e);
			
		}
	}

	@Override
	public void cancel() {
		progress.setComputationState(ComputationState.FINISHED_CANCEL);

	}

	@Override
	public void kill() {
		progress.setComputationState(ComputationState.FINISHED_CANCEL);

	}
	

	@Override
	public void receiveInputContinuous(IAlgoExecution continuousProducer, Object keyWave, IConnectionExecution connectionExec, Object value) {
		
		// received a refresh of the input; let's write it
		
		IGenlabTable table = null;
		
		try {
			table = (IGenlabTable)value;
			
			if (table == null) {
				messages.warnTech("should have received a table to display, but it is null; ignoring intermediate writing", getClass());
				return;
			}
		} catch (RuntimeException e) {
			messages.warnTech("should have received a table to display, but it is not correct; ignoring intermediate writing", getClass(), e);
			return;
		}
		
		final File file = (File)algoInst.getValueForParameter(WriteGnuplotSkeletonAlgo.PARAMETER_FILE);

		
		try {
			writeTableToFile(file, table);					
		} catch (ProgramException e) {

			// ignore failures for intermediate steps
			e.printStackTrace();
			messages.warnTech(e.getMessage(), getClass(), e);
			
		}
	}

}
