package bnj.plugins.huginImport;
/* Generated By:JJTree: Do not edit this line. NetParserVisitor.java */

public interface NetParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
