package bnj.plugins.huginImport;
/* Generated By:JJTree: Do not edit this line. NetParserTreeConstants.java */

public interface NetParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTFORMATV6_0 = 1;
  public int JJTFORMATV5_7 = 2;
  public int JJTVOID = 3;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "Formatv6_0",
    "Formatv5_7",
    "void",
  };
}
